mysql-container:
  build: /root/git/DockerTutorial/spring3app/mysql/.
  volumes:
    - /tmp/mysql:/var/lib/mysql
    - /tmp/logs/mysqld.log:/var/log/mysqld.log

my-tom:
  image: tomcat:7.0
  volumes:
  	- /tmp/webapps:/usr/local/tomcat/webapps
  	- /tmp/tomcat-log/:/usr/local/tomcat/logs
  links:
  	- mysql-container
  
nginx:
  build: /root/git/DockerTutorial/spring3app/nginx/.
  ports:
   - "80:80"
  links:
   - my-tom
